//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FilmSistemi.Resource.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Paneli.
        /// </summary>
        public static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktör.
        /// </summary>
        public static string aktor {
            get {
                return ResourceManager.GetString("aktor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string anasayfa {
            get {
                return ResourceManager.GetString("anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÇIKIŞ.
        /// </summary>
        public static string cikis {
            get {
                return ResourceManager.GetString("cikis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cıkış Tarihi.
        /// </summary>
        public static string cikis_tarihi {
            get {
                return ResourceManager.GetString("cikis_tarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAHA FAZLASI.
        /// </summary>
        public static string daha_fazlasi {
            get {
                return ResourceManager.GetString("daha_fazlasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dk.
        /// </summary>
        public static string dk {
            get {
                return ResourceManager.GetString("dk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film Listesi.
        /// </summary>
        public static string film_listesi {
            get {
                return ResourceManager.GetString("film_listesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FİLMLER.
        /// </summary>
        public static string filmler {
            get {
                return ResourceManager.GetString("filmler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOTOGRAFLAR &amp; VİDEOLAR.
        /// </summary>
        public static string foto_video {
            get {
                return ResourceManager.GetString("foto_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotoğraflar.
        /// </summary>
        public static string fotograf {
            get {
                return ResourceManager.GetString("fotograf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string giris {
            get {
                return ResourceManager.GetString("giris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GÜNÜN EN İYİLERi.
        /// </summary>
        public static string gun_en_iyi {
            get {
                return ResourceManager.GetString("gun_en_iyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haberler.
        /// </summary>
        public static string haber {
            get {
                return ResourceManager.GetString("haber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HABERLER.
        /// </summary>
        public static string haberler {
            get {
                return ResourceManager.GetString("haberler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori.
        /// </summary>
        public static string kategori {
            get {
                return ResourceManager.GetString("kategori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onceki.
        /// </summary>
        public static string onceki {
            get {
                return ResourceManager.GetString("onceki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oyunuz.
        /// </summary>
        public static string oylar {
            get {
                return ResourceManager.GetString("oylar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖZET.
        /// </summary>
        public static string ozet {
            get {
                return ResourceManager.GetString("ozet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paylas.
        /// </summary>
        public static string paylas {
            get {
                return ResourceManager.GetString("paylas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selam.
        /// </summary>
        public static string selam {
            get {
                return ResourceManager.GetString("selam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SON HABERLER.
        /// </summary>
        public static string son_haberler {
            get {
                return ResourceManager.GetString("son_haberler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonraki.
        /// </summary>
        public static string sonraki {
            get {
                return ResourceManager.GetString("sonraki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŞUAN VİZYONDAKİLERE GÖZ ATIN.
        /// </summary>
        public static string suan_oynayan_filmler {
            get {
                return ResourceManager.GetString("suan_oynayan_filmler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulke.
        /// </summary>
        public static string ulke {
            get {
                return ResourceManager.GetString("ulke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videolar.
        /// </summary>
        public static string video {
            get {
                return ResourceManager.GetString("video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yıl.
        /// </summary>
        public static string yıl {
            get {
                return ResourceManager.GetString("yıl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetmen.
        /// </summary>
        public static string yonetmen {
            get {
                return ResourceManager.GetString("yonetmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorum Ekle.
        /// </summary>
        public static string yorum_ekle {
            get {
                return ResourceManager.GetString("yorum_ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorumlar.
        /// </summary>
        public static string yorumlar {
            get {
                return ResourceManager.GetString("yorumlar", resourceCulture);
            }
        }
    }
}
