//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmSistemi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FilmSistemiEntities : DbContext
    {
        public FilmSistemiEntities()
            : base("name=FilmSistemiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actors> Actors { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<Contacts> Contacts { get; set; }
        public virtual DbSet<MovieCategory> MovieCategory { get; set; }
        public virtual DbSet<MoviePicture> MoviePicture { get; set; }
        public virtual DbSet<Movies> Movies { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<NewsPicture> NewsPicture { get; set; }
        public virtual DbSet<Stars> Stars { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Videos> Videos { get; set; }
        public virtual DbSet<WatchLists> WatchLists { get; set; }
        public virtual DbSet<ActorMovie> ActorMovie { get; set; }
        public virtual DbSet<Sliders> Sliders { get; set; }
    }
}
