//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public News()
        {
            this.NewsPicture = new HashSet<NewsPicture>();
        }
    
        public int NewsId { get; set; }
        public string NTitle { get; set; }
        public string NContent { get; set; }
        public Nullable<System.DateTime> NDate { get; set; }
    
        public virtual ICollection<NewsPicture> NewsPicture { get; set; }
    }
}
