//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsPicture
    {
        public int NPId { get; set; }
        public Nullable<int> NewsId { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<System.DateTime> NPDate { get; set; }
    
        public virtual News News { get; set; }
    }
}
